version: '3.8'
networks:
  order:
services:
  order-service:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5005:5005
    networks:
      - order
    volumes:
      - ./src/log:/usr/src/app/src/log
    restart: unless-stopped
  promtail:
    image: grafana/promtail
    volumes:
      - ./src/log:/var/order
      - ./promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - order
